"""fix due date in card table

Revision ID: 19697368cb23
Revises: b00d16e36e07
Create Date: 2024-10-03 10:51:23.819640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19697368cb23'
down_revision = 'b00d16e36e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('dueDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dueDate', sa.DATETIME(), nullable=True))
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
